local_backend: true
backend:
  name: github
  repo: fmir86/fabianmiranda.com-decapcms-nextjs
  branch: main
media_folder: public/images
public_folder: /images

collections:

  # Global Components
  - name: "global"
    label: "Global Components"
    files:

      - label: "Header"
        name: "header"
        file: "content/global/header.md"
        fields:
          - label: "Logo"
            name: "logo"
            widget: "object"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt Text", name: "alt", widget: "string" }
              - { label: "Width", name: "width", widget: "number" }
              - { label: "Height", name: "height", widget: "number" }
          - label: "Navigation"
            name: "navigation"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }

      - label: "Footer"
        name: "footer"
        file: "content/global/footer.md"
        fields:
          - { label: "Logo SVG", name: "logo_svg", widget: "image" }
          - label: "Navigation"
            name: "navigation"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
          - label: "Social Links"
            name: "social_links"
            widget: "list"
            fields:
              - { label: "Platform", name: "platform", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "Icon", name: "icon", widget: "string" }
          - { label: "Copyright", name: "copyright", widget: "string" }

  # Service Items (for individual service pages if needed)
  - name: "service_items"
    label: "Service Items"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "featured_image", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  # Case Studies (Portfolio)
  - name: "case_studies"
    label: "Case Studies"
    folder: "content/case-studies"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, hint: "Project completion date or publish date" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Content", name: "content", widget: "markdown", required: false, hint: "Full case study content with detailed information" }
      - { label: "Image", name: "image", widget: "image" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        field: { label: "Tag", name: "tag", widget: "string" }
      - { label: "Live URL", name: "live_url", widget: "string", required: false }
      - { label: "GitHub URL", name: "github_url", widget: "string", required: false }
      - label: "Highlights"
        name: "highlights"
        widget: "list"
        field: { label: "Highlight", name: "highlight", widget: "string" }
      - { label: "Impact", name: "impact", widget: "text" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false, required: false }
      - { label: "Order", name: "order", widget: "number", default: 0, value_type: "int", hint: "Used to control display order (lower numbers appear first)" }

  # Blog Posts
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm" }
      - { label: "Author", name: "author", widget: "string", default: "Fabian Miranda" }
      - { label: "Excerpt", name: "excerpt", widget: "text", hint: "Short summary for blog listing page" }
      - { label: "Featured Image", name: "featured_image", widget: "image", required: false }
      - { label: "Content", name: "body", widget: "markdown" }
      - label: "Categories"
        name: "categories"
        widget: "list"
        field: { label: "Category", name: "category", widget: "string" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        field: { label: "Tag", name: "tag", widget: "string" }
      - { label: "Published", name: "published", widget: "boolean", default: true }
      - { label: "Featured", name: "featured", widget: "boolean", default: false, required: false }
