local_backend: true
backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: /images

collections:

  # Global Components
  - name: "global"
    label: "Global Components"
    files:

      - label: "Header"
        name: "header"
        file: "content/global/header.md"
        fields:
          - label: "Logo"
            name: "logo"
            widget: "object"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt Text", name: "alt", widget: "string" }
              - { label: "Width", name: "width", widget: "number" }
              - { label: "Height", name: "height", widget: "number" }
          - label: "Navigation"
            name: "navigation"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }

      - label: "Footer"
        name: "footer"
        file: "content/global/footer.md"
        fields:
          - { label: "Logo SVG", name: "logo_svg", widget: "image" }
          - label: "Navigation"
            name: "navigation"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
          - label: "Social Links"
            name: "social_links"
            widget: "list"
            fields:
              - { label: "Platform", name: "platform", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "Icon", name: "icon", widget: "string" }
          - { label: "Copyright", name: "copyright", widget: "string" }

  # Pages
  - name: "pages"
    label: "Pages"
    files:

      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: 'Cats'
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }

      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: 'Cats'
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }

      - label: "Services"
        name: "services"
        file: "content/services.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Keywords", name: "keywords", widget: "string" }
          - { label: "OG Title", name: "og_title", widget: "string" }
          - { label: "OG Description", name: "og_description", widget: "text" }
          - { label: "Canonical URL", name: "canonical", widget: "string" }
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Video", name: "video", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Title Highlight 1", name: "title_highlight_1", widget: "string" }
              - { label: "Title Highlight 2", name: "title_highlight_2", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "text" }
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Icon", name: "icon", widget: "string" }
              - { label: "Icon Background Color", name: "icon_bg_color", widget: "string" }
              - { label: "Image", name: "image", widget: "string" }
              - { label: "Category Tag", name: "category_tag", widget: "string" }
              - label: "Description"
                name: "description"
                widget: "list"
                field: { label: "Paragraph", name: "paragraph", widget: "text" }
              - label: "Features"
                name: "features"
                widget: "list"
                fields:
                  - label: "Feature Group"
                    name: "feature_group"
                    widget: "list"
                    fields:
                      - { label: "Title", name: "title", widget: "string" }
                      - { label: "Description", name: "description", widget: "text" }
              - { label: "CTA Text", name: "cta_text", widget: "string" }
              - { label: "CTA Link", name: "cta_link", widget: "string" }
          - label: "CTA Banner"
            name: "cta_banner"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Primary CTA"
                name: "primary_cta"
                widget: "object"
                fields:
                  - { label: "Text", name: "text", widget: "string" }
                  - { label: "Link", name: "link", widget: "string" }
              - label: "Secondary CTA"
                name: "secondary_cta"
                widget: "object"
                fields:
                  - { label: "Text", name: "text", widget: "string" }
                  - { label: "Link", name: "link", widget: "string" }

      - label: "Work Page"
        name: "work"
        file: "content/work.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }

      - label: "Blog Page"
        name: "blog_page"
        file: "content/blog.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Heading", name: "heading", widget: "string" }

      - label: "Contact"
        name: "contact"
        file: "content/contact.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Intro Text", name: "intro_text", widget: "text" }
          - { label: "Main Image", name: "main_image", widget: "string" }
          - label: "Form Configuration"
            name: "form"
            widget: "object"
            fields:
              - { label: "Netlify", name: "netlify", widget: "boolean" }
              - { label: "Honeypot", name: "honeypot", widget: "string" }
              - { label: "Form Name", name: "name", widget: "string" }
              - label: "Fields"
                name: "fields"
                widget: "list"
                fields:
                  - { label: "Type", name: "type", widget: "select", options: ["text", "email", "select", "textarea"] }
                  - { label: "ID", name: "id", widget: "string" }
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Placeholder", name: "placeholder", widget: "string" }
                  - { label: "Required", name: "required", widget: "boolean" }
                  - label: "Options"
                    name: "options"
                    widget: "list"
                    required: false
                    field: { label: "Option", name: "option", widget: "string" }
              - { label: "Submit Button", name: "submit_button", widget: "string" }
              - label: "Success Message"
                name: "success_message"
                widget: "object"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Text", name: "text", widget: "text" }
              - label: "Error Message"
                name: "error_message"
                widget: "object"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Text", name: "text", widget: "text" }

  # Service Items (for individual service pages if needed)
  - name: "service_items"
    label: "Service Items"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "featured_image", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  # Case Studies (Portfolio)
  - name: "case_studies"
    label: "Case Studies"
    folder: "content/case-studies"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, hint: "Project completion date or publish date" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Content", name: "content", widget: "markdown", required: false, hint: "Full case study content with detailed information" }
      - { label: "Image", name: "image", widget: "image" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        field: { label: "Tag", name: "tag", widget: "string" }
      - { label: "Live URL", name: "live_url", widget: "string", required: false }
      - { label: "GitHub URL", name: "github_url", widget: "string", required: false }
      - label: "Highlights"
        name: "highlights"
        widget: "list"
        field: { label: "Highlight", name: "highlight", widget: "string" }
      - { label: "Impact", name: "impact", widget: "text" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false, required: false }
      - { label: "Order", name: "order", widget: "number", default: 0, value_type: "int", hint: "Used to control display order (lower numbers appear first)" }

  # Blog Posts
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm" }
      - { label: "Author", name: "author", widget: "string", default: "Fabian Miranda" }
      - { label: "Excerpt", name: "excerpt", widget: "text", hint: "Short summary for blog listing page" }
      - { label: "Featured Image", name: "featured_image", widget: "image", required: false }
      - { label: "Content", name: "body", widget: "markdown" }
      - label: "Categories"
        name: "categories"
        widget: "list"
        field: { label: "Category", name: "category", widget: "string" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        field: { label: "Tag", name: "tag", widget: "string" }
      - { label: "Published", name: "published", widget: "boolean", default: true }
      - { label: "Featured", name: "featured", widget: "boolean", default: false, required: false }
